create database hb_student_tracker;

create table if not exists student (
    id integer primary key generated by default as identity,
    first_name varchar(45),
    last_name varchar(45),
    email varchar(45)
);
